# Numpy

#### 1.Создать вектор (одномерный массив) размера 100, заполненный нулями

In [ ]:
import numpy as np

a = np.zeros(100)
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0.]


#### 2.Создать вектор размера 100, заполненный единицами

In [ ]:
a = np.ones(100)
print(a)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1.]


#### 3.Создать вектор размера 100, заполненный числом 3

In [ ]:
a = np.full(100, 3)
print(a)

[3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3
 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3
 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3]


#### 4. Поменять 2 строки в матрице

In [ ]:
a = np.array([[0, 1, 2], [3, 4, 5], [10,4,6]])
tmp = a[0]
a[1] = tmp
a[0] = tmp
print(a)


[[ 0  1  2]
 [ 0  1  2]
 [10  4  6]]


#### 5. Создать вектор со значениями от 10 до 100

In [ ]:
d = np.arange(start=10, stop=101, step=1)
print(d)

[ 10  11  12  13  14  15  16  17  18  19  20  21  22  23  24  25  26  27
  28  29  30  31  32  33  34  35  36  37  38  39  40  41  42  43  44  45
  46  47  48  49  50  51  52  53  54  55  56  57  58  59  60  61  62  63
  64  65  66  67  68  69  70  71  72  73  74  75  76  77  78  79  80  81
  82  83  84  85  86  87  88  89  90  91  92  93  94  95  96  97  98  99
 100]


#### 6. Создать матрицу (двумерный массив) 4x4 со значениями от 0 до 16

In [ ]:
A = np.arange(16).reshape(4,4)
print(A)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


#### 7. Создать 3x3 единичную матрицу

In [ ]:
a = np.ones((3,3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


#### 8. Создать массив 3x3x3 со случайными значениями

In [ ]:
a = np.random.random((3,3,3))
print(a)

[[[0.80058766 0.77203714 0.42991042]
  [0.21992525 0.86320171 0.45361553]
  [0.35323257 0.87731929 0.69503902]]

 [[0.51357535 0.5766979  0.43396493]
  [0.47147507 0.19928399 0.36465255]
  [0.93991833 0.53405834 0.29555589]]

 [[0.06099982 0.47014901 0.16974594]
  [0.68407735 0.34158225 0.1890454 ]
  [0.23272343 0.49621845 0.030128  ]]]


#### 9. Создать массив 10x10 со случайными значениями, найти минимум и максимум

In [ ]:
a = np.random.random((10,10))
print(a)
max = np.max(a)
min = np.min(a)
print("this is max: ",max)
print("this is min: ", min)

[[0.07929609 0.23353146 0.52738681 0.11243841 0.6246029  0.78350621
  0.37644623 0.20527452 0.90970316 0.25626918]
 [0.47944662 0.21801808 0.2298346  0.73932537 0.19621918 0.84396924
  0.12448793 0.67614244 0.09567311 0.15939121]
 [0.39609343 0.03096704 0.88367121 0.8466056  0.54914185 0.16772491
  0.35322812 0.99834325 0.82306336 0.8088639 ]
 [0.2519966  0.22340442 0.25402553 0.22524716 0.26740574 0.75869495
  0.60305822 0.63227001 0.86788785 0.10555077]
 [0.16605829 0.7744185  0.25988334 0.72189626 0.90479105 0.87465479
  0.01687486 0.32547334 0.21360434 0.57416401]
 [0.71482373 0.47092157 0.65456809 0.36522036 0.86952953 0.97445325
  0.33878208 0.43813216 0.14169171 0.07943197]
 [0.30166536 0.28743674 0.22904497 0.05765983 0.93828661 0.11409637
  0.53355404 0.52228028 0.59938033 0.51565339]
 [0.91020077 0.05773464 0.90147414 0.88224692 0.78291938 0.33820858
  0.37727847 0.71765373 0.14505344 0.74425518]
 [0.36239684 0.54089105 0.30849265 0.15826252 0.78996204 0.67526563
  0.08358342

#### 10. Создать случайный вектор размера 30 и найти среднее значение всех элементов

In [ ]:
a = np.random.random(30)
print(a)
m = a.mean()
print(m)

[0.81289181 0.43491393 0.89452674 0.82091614 0.00751147 0.71859868
 0.70088742 0.36973035 0.50429209 0.14028295 0.73412499 0.39982624
 0.13157214 0.10469502 0.68851072 0.33282946 0.57055385 0.49658124
 0.46766129 0.47470665 0.32030179 0.95914203 0.6268382  0.23435518
 0.15195619 0.33450307 0.413031   0.24238256 0.54801178 0.80412522]
0.48134200682823247


#### 11. Дан массив размерности (6,7,8). Каков индекс (x,y,z) сотого элемента?

In [ ]:
print(np.unravel_index(100, (6,7,8)))

(1, 5, 4)


#### 12. Перемножить матрицы 5x3 и 3x2

In [ ]:
a = np.dot(np.ones((5,3)), np.ones((3,2)))
print(a)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


#### 13. Дан массив, поменять знак у элементов, значения которых между 3 и 8

In [ ]:
a = np.arange(11)
a[(3 < a) & (a <= 8)] *= -1
print(a)

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


#### 14. Создать 5x5 матрицу со значениями в строках от 0 до 4

In [ ]:
a = np.zeros((5,5))
a += np.arange(5)
print(a)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 15. Отнять среднее из каждой строки в матрице

In [ ]:
X = np.random.rand(5, 10)
print(X)

[[0.5965386  0.72593189 0.78848787 0.66259785 0.94553923 0.11279582
  0.51105505 0.00096009 0.72682483 0.86096014]
 [0.27747641 0.06048735 0.85434876 0.83413757 0.33284114 0.03653389
  0.67612502 0.79630512 0.57028239 0.33176468]
 [0.24404269 0.50850283 0.8231184  0.13722803 0.17654158 0.75778843
  0.94901566 0.71534828 0.58117429 0.94117333]
 [0.88886672 0.87752804 0.94550612 0.63809377 0.76576399 0.60120305
  0.88672975 0.16667138 0.77392042 0.93018336]
 [0.67923805 0.26063561 0.2319383  0.22294105 0.69822386 0.78555254
  0.25739065 0.58455596 0.07499207 0.80612557]]


In [ ]:
print(X.mean(axis=1, keepdims=True))
Y = X - X.mean(axis=1, keepdims=True)

[[0.59316914]
 [0.47703023]
 [0.58339335]
 [0.74744666]
 [0.46015937]]


In [ ]:
print(Y)

[[-0.08167195 -0.24290869 -0.23115795 -0.27108368  0.10138905 -0.11760523
   0.01626917  0.17117556  0.20872361  0.44687011]
 [-0.42723828 -0.25652244 -0.14605736  0.06261804  0.41919952  0.28909003
   0.3184398   0.422086   -0.44095666 -0.24065866]
 [ 0.20600439  0.19111885  0.07320566 -0.39062906 -0.02877557  0.39390999
  -0.2556154  -0.42318091 -0.09689042  0.33085247]
 [-0.39689474  0.3532119  -0.10262125 -0.22527435 -0.16776691 -0.01299562
   0.31316325 -0.17635141  0.09858882  0.3169403 ]
 [-0.15796913  0.48194695  0.20883685  0.13672305 -0.4819083   0.42921125
   0.41105322 -0.2522553  -0.37980243 -0.39583617]]
