In [ ]:
import numpy as np

# Домашнее задание на повторение numpy
В задании все пункты необходимо выполнить с помощью numpy, без использования циклов/map/и тд! 

Задание выполняется __самостоятельно__. Категорически запрещено пользоваться чужими решениями заданий (даже смотреть их), в том числе, размещенными в открытых источниках (если таковые обнаружатся). При обнаружении списывания выставляется 0 за задание (в случае списывания у одногруппника/однокурскника - __ему/ей тоже__), а также подается докладная записка в учебный офис. Проверка на списывание проводится и автоматическими средствами, и вручную.

### История

В конце каждого семестра каждый семинарист сталкивается с необходимостью выставить студентам накопленную в семестре оценку. Часто семинаристы делают это с помощью Excel или GoogleSheets, но поверьте, с этим возникают проблемы. В задании вам надо помочь семинаристу некоторого курса выполнить эту непростую работу с помощью numpy :)

Выполните ячейку ниже, чтобы загрузить данные и визуально проверить корректность их считывания.

По строкам - студенты, по столбцам - их оценки. В курсе семинарист провел три проверочных (первые три колонки), выдал три домашних работы (следующие три колонки), кроме того, у студентов есть оценка за коллоквиум (последняя колонка).

In [ ]:
marks = np.loadtxt("https://raw.githubusercontent.com/nadiinchi/iad2019/master/materials/data_hw1.txt")

In [ ]:
marks[:3]

array([[ 7. ,  8. , 10. ,  0. ,  0. ,  2.1,  1.5],
       [ 0. ,  6. ,  4.4,  4. ,  0. ,  5. ,  4.3],
       [ 3. ,  7. ,  8.7,  7.6,  7. ,  9.7, 10. ]])

### Число студентов (1 балл)
Сколько студентов в группе семинариста?

In [ ]:
# Записать ответ в переменную num_studs

rows, columns = np.shape(marks)
num_studs = rows


In [ ]:
print(num_studs)

28


### Очень сложная проверочная, или просто добрый семинарист (1.5 балла)
Семинарист помнит, что первая проверочная получилась очень сложной, и максимальный балл в группе был далеко не 10. Поэтому он решил перенормировать баллы за эту проверочную на максимум по группе (поделить на максимум и умножить на 10) - чтобы у студента с максимальной оценкой получилось 10, а у остальных - просто оценка больше.

Каков максимальный балл за первую проверочную?

In [ ]:
# Записать ответ в переменную max_mark
max_mark = marks.max(axis=0)[0]

In [ ]:
print(max_mark)

7.0


Разделите первый столбец на max_mark (для этого надо выделить столбец, поставить после соответствующего выражения знак = и присвоить новое значение столбца)

In [ ]:
marks[:, 0]=marks[:, 0]/max_mark * 10

In [ ]:
marks

array([[10.        ,  8.        , 10.        ,  0.        ,  0.        ,
         2.1       ,  1.5       ],
       [ 0.        ,  6.        ,  4.4       ,  4.        ,  0.        ,
         5.        ,  4.3       ],
       [ 4.28571429,  7.        ,  8.7       ,  7.6       ,  7.        ,
         9.7       , 10.        ],
       [ 4.85714286,  1.3       ,  7.        ,  3.4       ,  0.        ,
         9.4       ,  9.        ],
       [ 9.71428571,  9.1       ,  8.2       ,  0.        ,  0.        ,
         7.9       ,  7.9       ],
       [10.        , 10.        , 10.        ,  9.        ,  9.5       ,
        10.        ,  8.        ],
       [ 8.57142857, 10.        ,  9.7       ,  8.7       ,  7.        ,
         8.5       ,  9.7       ],
       [ 0.        ,  9.3       ,  5.7       ,  0.        ,  0.        ,
         0.        ,  0.        ],
       [ 7.14285714, 10.        , 10.        ,  9.9       , 10.5       ,
        10.        ,  9.        ],
       [ 0.        ,  8.7   

### Подсчет накопленной оценки (1.5 балла)
Для вычисления накопленной надо посчитать средние оценки за проверочные для каждого студента и средние за домашние работы (может пригодиться np.mean). Накопленная оценка есть 0.3\*Проверочные + 0.4\*Домашние + 0.3\*Коллоквиум. Вычислите накопленные оценки и добавьте их в последний столбец матрицы (нужно добавить еще один новый столбец).

In [ ]:
# Веса следует брать из переменной weights, а не вписывать вручную
weights = [0.3, 0.4, 0.3]

In [ ]:
a=np.mean(marks[:, :3],axis=1)*weights[0]+np.mean(marks[:, 3:6],axis=1)*weights[1]+np.mean(marks[:, 6:7],axis=1)*weights[2]
#print(a.shape)
#print(marks.shape)
#print(a)

In [ ]:
#np.append(marks, a, axis = 0)
marks=np.concatenate((marks, a[:,None]), axis=1)

In [ ]:
print(marks)

[[10.          8.         10.          0.          0.          2.1
   1.5         3.53      ]
 [ 0.          6.          4.4         4.          0.          5.
   4.3         3.53      ]
 [ 4.28571429  7.          8.7         7.6         7.          9.7
  10.          8.23857143]
 [ 4.85714286  1.3         7.          3.4         0.          9.4
   9.          5.72238095]
 [ 9.71428571  9.1         8.2         0.          0.          7.9
   7.9         6.1247619 ]
 [10.         10.         10.          9.          9.5        10.
   8.          9.2       ]
 [ 8.57142857 10.          9.7         8.7         7.          8.5
   9.7         8.96380952]
 [ 0.          9.3         5.7         0.          0.          0.
   0.          1.5       ]
 [ 7.14285714 10.         10.          9.9        10.5        10.
   9.          9.46761905]
 [ 0.          8.7         8.          9.7        10.          9.5
  10.          8.56333333]
 [ 4.28571429  6.9         7.9         0.          0.          0

### Студенты, которых, вероятно, отчислят (1.5 балла)

Сколько в группе студентов с накопленной оценкой 0? Вам может понадобиться тот факт, что применение np.sum к бинарному вектору дает число значений True в нем, например:

In [ ]:
np.sum([True, False, True]) # 2 значения True

2

In [ ]:
marks[:, -1]==0

array([False, False, False, False, False, False, False, False, False,
       False, False, False,  True, False, False, False, False, False,
        True, False,  True, False, False, False, False, False, False,
       False])

Также обратим внимание на операцию поэлементного сравнения, возвращающую массив из True и False:

In [ ]:
a = np.array([1, 2, 3])
b = np.array([2, 3, 3])
print(a == b)
print(a > b)

[False False  True]
[False False False]


### Студенты, которые получат автоматы (1.5 балла)
Автомат получат студенты, у которых накопленная оценка больше 7. Добавьте еще один столбец - в нем стоит 1, если студент получает автомат, и 0 иначе.

In [ ]:
marks

array([[10.        ,  8.        , 10.        ,  0.        ,  0.        ,
         2.1       ,  1.5       ,  3.53      ],
       [ 0.        ,  6.        ,  4.4       ,  4.        ,  0.        ,
         5.        ,  4.3       ,  3.53      ],
       [ 4.28571429,  7.        ,  8.7       ,  7.6       ,  7.        ,
         9.7       , 10.        ,  8.23857143],
       [ 4.85714286,  1.3       ,  7.        ,  3.4       ,  0.        ,
         9.4       ,  9.        ,  5.72238095],
       [ 9.71428571,  9.1       ,  8.2       ,  0.        ,  0.        ,
         7.9       ,  7.9       ,  6.1247619 ],
       [10.        , 10.        , 10.        ,  9.        ,  9.5       ,
        10.        ,  8.        ,  9.2       ],
       [ 8.57142857, 10.        ,  9.7       ,  8.7       ,  7.        ,
         8.5       ,  9.7       ,  8.96380952],
       [ 0.        ,  9.3       ,  5.7       ,  0.        ,  0.        ,
         0.        ,  0.        ,  1.5       ],
       [ 7.14285714, 10.        

In [ ]:
a=np.where(marks[:, -1]>=7, 1,0)
print(a)

[0 0 1 0 0 1 1 0 1 1 0 1 0 1 1 0 1 0 0 0 0 1 1 1 0 0 1 1]


In [ ]:
marks = np.concatenate((marks, a[:,None]), axis=1)
print(marks)

[[10.          8.         10.          0.          0.          2.1
   1.5         3.53        0.        ]
 [ 0.          6.          4.4         4.          0.          5.
   4.3         3.53        0.        ]
 [ 4.28571429  7.          8.7         7.6         7.          9.7
  10.          8.23857143  1.        ]
 [ 4.85714286  1.3         7.          3.4         0.          9.4
   9.          5.72238095  0.        ]
 [ 9.71428571  9.1         8.2         0.          0.          7.9
   7.9         6.1247619   0.        ]
 [10.         10.         10.          9.          9.5        10.
   8.          9.2         1.        ]
 [ 8.57142857 10.          9.7         8.7         7.          8.5
   9.7         8.96380952  1.        ]
 [ 0.          9.3         5.7         0.          0.          0.
   0.          1.5         0.        ]
 [ 7.14285714 10.         10.          9.9        10.5        10.
   9.          9.46761905  1.        ]
 [ 0.          8.7         8.          9.7        

### Студенты, которые будут освобождены от задач на экзамене (1.5 балла)
Семинарист решил, что первая половина группы в рейтинге по накопленной оценке будет освобождена от решения задач на экзамене. Выделите этих студентов в отдельный массив. Для этого надо отсортировать строки массива (np.argsort) и взять первую половину.

In [ ]:
marks = marks[marks[:, 7].argsort()[::-1]]
print(marks)

[[10.         10.         10.          9.7        10.         10.
  10.          9.96        1.        ]
 [ 9.28571429  8.7         9.5        10.5         9.8        10.
  10.          9.78857143  1.        ]
 [10.          9.7        10.          8.1        10.         10.
   9.5         9.56666667  1.        ]
 [ 7.14285714 10.         10.          9.9        10.5        10.
   9.          9.46761905  1.        ]
 [ 5.71428571 10.         10.          9.9         9.7        10.
   9.          9.21809524  1.        ]
 [10.         10.         10.          9.          9.5        10.
   8.          9.2         1.        ]
 [ 4.28571429  8.7        10.          9.4        10.7        10.
   9.          9.01190476  1.        ]
 [ 8.57142857 10.          9.7         8.7         7.          8.5
   9.7         8.96380952  1.        ]
 [ 5.          9.3        10.          9.9        10.         10.
   8.          8.81666667  1.        ]
 [ 8.57142857  5.         10.          9.7        10. 

In [ ]:
best_students = marks[:14]
best_students

array([[10.        , 10.        , 10.        ,  9.7       , 10.        ,
        10.        , 10.        ,  9.96      ,  1.        ],
       [ 9.28571429,  8.7       ,  9.5       , 10.5       ,  9.8       ,
        10.        , 10.        ,  9.78857143,  1.        ],
       [10.        ,  9.7       , 10.        ,  8.1       , 10.        ,
        10.        ,  9.5       ,  9.56666667,  1.        ],
       [ 7.14285714, 10.        , 10.        ,  9.9       , 10.5       ,
        10.        ,  9.        ,  9.46761905,  1.        ],
       [ 5.71428571, 10.        , 10.        ,  9.9       ,  9.7       ,
        10.        ,  9.        ,  9.21809524,  1.        ],
       [10.        , 10.        , 10.        ,  9.        ,  9.5       ,
        10.        ,  8.        ,  9.2       ,  1.        ],
       [ 4.28571429,  8.7       , 10.        ,  9.4       , 10.7       ,
        10.        ,  9.        ,  9.01190476,  1.        ],
       [ 8.57142857, 10.        ,  9.7       ,  8.7       ,  7

### Сложность заданий (1.5 балла)
Наконец, семинарист хочет оценить сложность заданий, проверочных и коллоквиума по своей особой системе. Он присвоил каждому студенту вес (веса суммируются в 1) и хочет посчитать для каждого задания, проверочной и коллоквиума среднюю оценку с весами.
Пример, что имеется в виду: если есть 4 студента с весами [0.1, 0.2, 0.3, 0.4] и оценками [3, 7, 9, 10], то средняя оценка за задание с весами получится 

In [ ]:
0.1 * 3 + 0.2 * 7 + 0.3 * 9 + 0.4 * 10 

8.4

Веса:

In [128]:
weights = np.array([1.]*7+[2.]*4+[3.]*7+[4.]*(marks.shape[0]-18))
# разделите веса на их сумму, чтобы они суммировались к 1
weights

array([1., 1., 1., 1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3., 3., 3.,
       3., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4.])

Посчитайте указанным образом сложность каждого "столбца".

In [136]:
weights / sum(weights)

array([0.01315789, 0.01315789, 0.01315789, 0.01315789, 0.01315789,
       0.01315789, 0.01315789, 0.02631579, 0.02631579, 0.02631579,
       0.02631579, 0.03947368, 0.03947368, 0.03947368, 0.03947368,
       0.03947368, 0.03947368, 0.03947368, 0.05263158, 0.05263158,
       0.05263158, 0.05263158, 0.05263158, 0.05263158, 0.05263158,
       0.05263158, 0.05263158, 0.05263158])

In [141]:
dificult = (weights / sum(weights))*marks[:, 7]

In [142]:
print(dificult)

[0.13105263 0.12879699 0.12587719 0.12457393 0.12129073 0.12105263
 0.11857769 0.23588972 0.23201754 0.2293985  0.22721805 0.33802632
 0.33620301 0.32520677 0.24176692 0.22588346 0.19105263 0.14919173
 0.18578947 0.18578947 0.16035088 0.10045113 0.07894737 0.07526316
 0.07052632 0.         0.         0.        ]
